debugingv21

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,59 +1,53 @@
 version: 2.1
 
 commands:
-  install_awscli:
-    description: install AWS-CLI
+  install-awscli:
+    description: install AWS CLI v2
     steps:
       - run:
-          name: Install AWS-CLI
+          name: install AWS CLI v2
           command: |
-            sudo apt-get update && sudo apt-get install -yy less
             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
             unzip awscliv2.zip
             sudo ./aws/install
 
-  install_ansible: #we will install ansible
-    description: Install Ansible
+  install-ansible:
+    description: install ansible
     steps:
       - run:
-          name: Install Ansible
+          name: install ansible
           command: |
-            python3 -m pip install --user ansible 
             sudo apt update
             sudo apt install software-properties-common -y
             sudo add-apt-repository --yes --update ppa:ansible/ansible
             sudo apt install ansible -y
 
-  install_nodejs: #we will install nodejs 13.8.0
-    description: Install Node.js 13.8.0
+  install-nodejs:
+    description: Install Node.js 14
     steps:
       - run:
-          name: Install Node.js 13.8.0
+          name: Install Node.js 14
           command: |
-            # Install Node.js LTS version as our base Node.js version
-            curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
-            sudo apt install -y nodejs
-            # Use n version manager to use Node.js v13.8.0
-            sudo npm install --global n
-            sudo n 13.8.0
+            curl -fsSl https://deb.nodesource.com/setup_14.x | sudo -E bash -
+            sudo apt install nodejs -y
 
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
       Workflow_ID:
         type: string
-        default: ${CIRCLE_WORKFLOW_ID:0:5}
+        default: ${CIRCLE_WORKFLOW_ID:0:7}
     steps:
       - run:
           name: Destroy environments
           when: on_fail
           command: |
-            # aws cloudformation delete-stack --stack-name backend-${CIRCLE_WORKFLOW_ID:0:4}
-            # aws s3 rm s3://udapeople-<<parameters.Workflow_ID>> --recursive
-            # aws cloudformation delete-stack --stack-name frontend-<< parameters.Workflow_ID >>
+            aws s3 rm s3://udapeople-<<parameters.Workflow_ID>> --recursive
+            aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.Workflow_ID >>
+            aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.Workflow_ID >>
 
   revert-migrations:
-    description: Revert the last migration
+    description: Revert the last migration, if any were executed during the current workflow
     parameters:
       Workflow_ID:
         type: string
@@ -64,13 +58,16 @@ commands:
           when: on_fail
           command: |
             SUCCESS=$(curl --insecure  https://kvdb.io/${KVDB_BUCKET}/migration_<< parameters.Workflow_ID >>)
-            echo "$SUCCESS"
+
             # Logic for reverting the database state
-            if (( $SUCCESS == 1 ));
+            if [ "$SUCCESS" != "Not Found" ];
             then
-              cd ~/project/backend
-              npm install
-              npm run migration:revert
+              if (( $SUCCESS == 1 ));
+              then
+                cd ~/project/backend
+                npm install
+                npm run migration:revert
+              fi
             fi
 
 jobs:
@@ -80,7 +77,7 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-build]
+          keys: [frontend-deps]
       - run:
           name: Build front-end
           command: |
@@ -89,7 +86,7 @@ jobs:
             npm run build
       - save_cache:
           paths: [frontend/node_modules]
-          key: frontend-build
+          key: frontend-deps
 
   build-backend:
     docker:
@@ -97,7 +94,7 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-build]
+          keys: [backend-deps]
       - run:
           name: Back-end build
           command: |
@@ -106,7 +103,7 @@ jobs:
             npm run build
       - save_cache:
           paths: [backend/node_modules]
-          key: backend-build
+          key: backend-deps
 
   test-frontend:
     docker:
@@ -114,14 +111,13 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-build]
+          keys: [frontend-deps]
       - run:
-          name: Test front-end
+          name: Front-end Unit Test
           command: |
             cd frontend
             npm install
-            npm install oauth-sign
-            npm run test
+            npm test
 
   test-backend:
     docker:
@@ -129,13 +125,13 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-build]
+          keys: [backend-deps]
       - run:
-          name: Test Back-end
+          name: Back-end Unit Test
           command: |
-            exit 0
             cd backend
-            npm run test
+            npm install
+            npm test
 
   scan-frontend:
     docker:
@@ -143,9 +139,9 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-build]
+          keys: [frontend-deps]
       - run:
-          name: Scan front-end
+          name: Front-end Scan
           command: |
             cd frontend
             npm install
@@ -162,126 +158,126 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-build]
+          keys: [backend-deps]
       - run:
-          name: Scan Back-end
+          name: Back-end Scan
           command: |
             cd backend
             npm install
-            # npm install oauth-sign@^0.9.0
             npm audit fix --force --audit-level=critical
             npm audit fix --force --audit-level=critical
             npm audit --audit-level=critical
 
   deploy-infrastructure:
     docker:
-      - image: amazon/aws-cli
+      - image: cimg/base:stable
     steps:
       - checkout
-      - run:
-          name: Install tar utility
-          command: |
-            yum install -y tar gzip
+      - install-awscli
       - run:
           name: Ensure back-end infrastructure exists
           command: |
-            # aws cloudformation deploy \
-            #   --template-file .circleci/files/backend.yml \
-            #   --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:4}" \
-            #   --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:4}"  \
-            #   --tags project=udapeople
+            aws cloudformation deploy \
+              --template-file .circleci/files/backend.yml \
+              --tags project=udapeople \
+              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
+
       - run:
-          name: Ensure front-end infrastructure exist
+          name: Ensure front-end infrastructure exists
           command: |
-            # aws cloudformation deploy \
-            #   --template-file .circleci/files/frontend.yml \
-            #   --tags project=udapeople \
-            #   --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:4} \
-            #   --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:4}"
+            aws cloudformation deploy \
+              --template-file .circleci/files/frontend.yml \
+              --tags project=udapeople \
+              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
+
       - run:
           name: Add back-end ip to ansible inventory
           command: |
-            aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> .circleci/ansible/inventory.txt
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text)
+            echo $BACKEND_PUBLIC_IP >> .circleci/ansible/inventory.txt
+            cat .circleci/ansible/inventory.txt
+
       - persist_to_workspace:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
+
       - destroy-environment
 
   configure-infrastructure:
     docker:
-      - image: python:3.7-alpine3.11
+      - image: cimg/base:stable
     steps:
       - checkout
+      - install-ansible
       - add_ssh_keys:
           fingerprints: ["46:bc:eb:ec:20:24:73:b8:31:3e:65:94:81:af:9f:25"]
-
       - attach_workspace:
           at: ~/
       - run:
-          name: Install dependencies
-          command: |
-            apk add --update tar gzip
-            apk add --update ansible
-
-      - run:
           name: Configure server
           command: |
-            ansible-playbook .circleci/ansible/configure-server.yml -i .circleci/ansible/inventory.txt
+            cd .circleci/ansible
+            cat inventory.txt
+            ansible-playbook -i inventory.txt configure-server.yml
+
       - destroy-environment
+      # Here's where you will add some code to rollback on failure
 
   run-migrations:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [backend-build]
-      - run:
-          name: Run migrations
-          command: |
-            # export TYPEORM_HOST=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
-            cd backend
-            npm install
-            npm run premigrations
-            npm run migrations
-            # cd backend
-            # npm install
-            # # Run and save the migration output
-            # npm run migrations > migrations_dump.txt
-            # cat migrations_dump.txt
-      - run:
-          name: Send migration results to memstash
-          command: |
-            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
-            then
-              # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
-              curl https://kvdb.io/Ea61qmNDn5FQ2NoYmHGhJJ/migration_${CIRCLE_WORKFLOW_ID:0:4}  -d '1'
-            fi
-      - destroy-environment
-
-  deploy-frontend:
     docker:
       - image: cimg/node:13.8.0
     steps:
       - checkout
-      - run: sudo apt-get install tar gzip -y
+      - install-awscli
+      - run:
+          name: Run migrations
+          command: |
+            cd backend
+            npm install
+            npm run migrations > migrations_dump.txt
+      - run:
+          name: Send migration status to kvdb.io
+          command: |
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            then
+              curl https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
+            fi
+
+      - destroy-environment
+      - revert-migrations
+
+      #nothing
+      # Here's where you will add some code to rollback on failure
+  #
+  deploy-frontend:
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - checkout
+      - install-awscli
+      - install-nodejs
       - restore_cache:
-          keys: [frontend-build]
+          keys: [frontend-deps]
       - run:
           name: Install dependencies
           command: |
-            sudo apt-get update && sudo apt-get install -yy less
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
+            cd frontend
+            npm install
       - run:
           name: Get backend url
           command: |
-            export BACKEND_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "API_URL = ${API_URL}"
-            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text)
+
+            echo "API_URL=http://${BACKEND_PUBLIC_IP}:3030" >> frontend/.env
             cat frontend/.env
       - run:
           name: Deploy frontend objects
@@ -290,127 +286,120 @@ jobs:
             npm run build
             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
 
+      - destroy-environment
       - revert-migrations
 
-      - destroy-environment
-
-  deploy-backend: # create deploy-backend
+  deploy-backend:
     docker:
-      - image: cimg/python:3.10
+      - image: cimg/base:stable
     steps:
       - checkout
-      - run: sudo apt-get install tar gzip -y
-      - install_awscli
-      - install_ansible
-      - install_nodejs
+      - install-awscli
+      - install-ansible
+      - install-nodejs
       - add_ssh_keys:
           fingerprints: ["46:bc:eb:ec:20:24:73:b8:31:3e:65:94:81:af:9f:25"]
       - attach_workspace:
           at: ~/
       - restore_cache:
-          keys: [backend-build]
+          keys: [backend-deps]
       - run:
-          name: Deploy backend
+          name: Install dependencies
           command: |
             cd backend
             npm install
+      - run:
+          name: Package Backend
+          command: |
+            cd backend
             npm run build
-            tar -vczf  artifact.tar.gz dist/* package*
-            cd .. 
-            cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
+            tar -czf artifact.tar.gz dist/* package*
 
+            cd ..
+            cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
+      - run:
+          name: Deploy backend
+          command: |
             export TYPEORM_MIGRATIONS_DIR=./migrations
-            export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
+            export TYPEORM_ENTITIES=./modules/domain/*/.entity{.ts,.js}
             export TYPEORM_MIGRATIONS=./migrations/*.ts
+
             cd .circleci/ansible
             cat inventory.txt
-            sudo apt update  && sudo apt upgrade
-            ansible-playbook -i  inventory.txt deploy-backend.yml
+            ansible-playbook -i inventory.txt deploy-backend.yml
 
       - destroy-environment
+      - revert-migrations
 
-  smoke-test: # createe smoke-test
+  smoke-test:
     docker:
-      - image: amazon/aws-cli
+      - image: cimg/base:stable
     steps:
       - checkout
-      - run:
-          name: "Install curl"
-          command: |
-            yum install -y curl
+      - install-awscli
+      - install-nodejs
       - run:
           name: Backend smoke test.
           command: |
-            export BACKEND_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
-            export API_URL="http://${BACKEND_IP}:3030"
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text)
+            export API_URL=http://${BACKEND_PUBLIC_IP}:3030
             echo "API_URL = ${API_URL}"
-            if curl "${API_URL}/api/status" | grep "ok"
-            then
-                exit 0
-            else
-                exit 1
-            fi
-      - run:
-          name: Frontend smoke test.
-          command: |
-            URL="http://udapeople-17b5.s3-website-us-east-1.amazonaws.com"            
-            echo ${URL} 
-            if curl -s ${URL} | grep "Welcome"
+            if curl -s ${API_URL}/api/status | grep "ok"
             then
               exit 0
             else
               exit 1
             fi
-      - destroy-environment
-      - revert-migrations
 
+      - run:
+          name: Frontend smoke test.
+          command: |
+            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+            then
+              exit 0
+            else
+              exit 1
+            fi
+
+      #      - destroy-environment
+      - revert-migrations
+#
 #  cloudfront-update:
 #    docker:
-#      - image: amazon/aws-cli
+#      # Docker image here that supports AWS CLI
 #    steps:
-#      - checkout
+#      # Checkout code from git
 #      - run:
 #          name: Install dependencies
 #          command: |
-#            export OLD_WORKFLOW_ID=$(aws cloudformation \
-#                      list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-#                      --no-paginate --output text)
-#            echo "Old Wokflow ID: $OLD_WORKFLOW_ID"
-#            curl -k https://kvdb.io/${KVDB_BUCKET}/old_workflow_id -d "${OLD_WORKFLOW_ID}"
+#            # your code here
 #      - run:
 #          name: Update cloudfront distribution
 #          command: |
-#            aws cloudformation deploy \
-#              --template-file .circleci/files/cloudfront.yml \
-#              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:4}" \
-#              --stack-name Initialstack
-#
-#
-#
-#
-#
-#
+#            # your code here
 #      # Here's where you will add some code to rollback on failure
 #
-#  cleanup:
+#cleanup:
 #    docker:
-#      - image: mareimorsy/aws-node
+#      # Docker image here
 #    steps:
-#      - checkout
+#      # Checkout code from git
+#      - run:
+#          name: Get old stack workflow id
+#          command: |
+#            # your code here
+#            export OldWorkflowID="the id here"
+#            export STACKS=[] #put the list of stacks here
 #      - run:
 #          name: Remove old stacks and files
 #          command: |
-#            export STACKS=($(aws cloudformation list-stacks \
-#                --query "StackSummaries[*].StackName" \
-#                --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
-#            echo Stack names: "${STACKS[@]}"
-#            export OldWorkflowID=$(curl --insecure https://kvdb.io/${KVDB_BUCKET}/old_workflow_id)
-#            echo Old Workflow ID: $OldWorkflowID
 #            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
 #            then
-#              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-#              aws cloudformation delete-stack --stack-name "backend-${OldWorkflowID}"
-#              aws cloudformation delete-stack --stack-name "frontend-${OldWorkflowID}"
+#              # your code here
 #            fi
 
 workflows:
@@ -426,6 +415,7 @@ workflows:
           requires: [build-backend]
       - scan-frontend:
           requires: [build-frontend]
+
       - deploy-infrastructure:
           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
           filters:
@@ -441,7 +431,7 @@ workflows:
           requires: [run-migrations]
       - smoke-test:
           requires: [deploy-backend, deploy-frontend]
-      # - cloudfront-update:
-      #     requires: [smoke-test]
-      #- cleanup
-      # requires: [cloudfront-update]
+#      - cloudfront-update:
+#          requires: [smoke-test]
+#      - cleanup:
+#          requires: [cloudfront-update]
