debugingv6

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,41 +1,35 @@
 version: 2.1
 
 commands:
-  install_awscli:
-    description: Install AWS CLI v2
+  install-awscli:
+    description: install AWS CLI v2
     steps:
       - run:
-          name: Install AWS CLI v2
+          name: install AWS CLI v2
           command: |
             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
             unzip awscliv2.zip
             sudo ./aws/install
 
-  install_nodejs:
-    description: Install Node.js 13
+  install-ansible:
+    description: install ansible
     steps:
       - run:
-          name: Install Node.js 13
+          name: install ansible
           command: |
-            # Install Node.js LTS version as our base Node.js version
-            curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
-            sudo apt-get install -y nodejs
-
-            # Use n version manager to use Node.js v13.8.0
-            sudo npm install -g n
-            sudo n 13.8.0
-
-  install_ansible:
-    description: Install Ansible
-    steps:
-      - run:
-          name: Install Ansible
-          command: |
-            sudo apt-get clean 
-            sudo apt-get update
+            sudo apt update
             sudo apt install software-properties-common -y
             sudo add-apt-repository --yes --update ppa:ansible/ansible
             sudo apt install ansible -y
+
+  install-nodejs:
+    description: Install Node.js 14
+    steps:
+      - run:
+          name: Install Node.js 14
+          command: |
+            curl -fsSl https://deb.nodesource.com/setup_14.x | sudo -E bash -
+            sudo apt install nodejs -y
 
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
@@ -52,10 +46,8 @@ commands:
             aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.Workflow_ID >>
             aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.Workflow_ID >>
 
-      #- destroy-environment
-
   revert-migrations:
-    description: Revert the last migration if successfully run in the current workflow.
+    description: Revert the last migration, if any were executed during the current workflow
     parameters:
       Workflow_ID:
         type: string
@@ -66,7 +58,8 @@ commands:
           when: on_fail
           command: |
             SUCCESS=$(curl --insecure  https://kvdb.io/${KVDB_BUCKET}/migration_<< parameters.Workflow_ID >>)
-            # For reverting database state
+
+            # Logic for reverting the database state
             if [ "$SUCCESS" != "Not Found" ];
             then
               if (( $SUCCESS == 1 ));
@@ -86,7 +79,7 @@ jobs:
       - restore_cache:
           keys: [frontend-deps]
       - run:
-          name: front-end Build
+          name: Build front-end
           command: |
             cd frontend
             npm install
@@ -105,8 +98,8 @@ jobs:
       - run:
           name: Back-end build
           command: |
-            cd backend 
-            npm install 
+            cd backend
+            npm install
             npm run build
       - save_cache:
           paths: [backend/node_modules]
@@ -120,7 +113,7 @@ jobs:
       - restore_cache:
           keys: [frontend-deps]
       - run:
-          name: front-end Unit test
+          name: Front-end Unit Test
           command: |
             cd frontend
             npm install
@@ -134,10 +127,10 @@ jobs:
       - restore_cache:
           keys: [backend-deps]
       - run:
-          name: Back-end Unit test
+          name: Back-end Unit Test
           command: |
-            cd backend 
-            npm install 
+            cd backend
+            npm install
             npm test
 
   scan-frontend:
@@ -152,8 +145,8 @@ jobs:
           command: |
             cd frontend
             npm install
-            npm audit fix --force --audit-level=cirtical
-            npm audit fix --force --audit-level=cirtical
+            npm audit fix --force --audit-level=critical
+            npm audit fix --force --audit-level=critical
             npm audit --audit-level=critical
 
   scan-backend:
@@ -168,8 +161,8 @@ jobs:
           command: |
             cd backend
             npm install
-            npm audit fix --force --audit-level=cirtical
-            npm audit fix --force --audit-level=cirtical
+            npm audit fix --force --audit-level=critical
+            npm audit fix --force --audit-level=critical
             npm audit --audit-level=critical
 
   deploy-infrastructure:
@@ -177,7 +170,7 @@ jobs:
       - image: cimg/base:stable
     steps:
       - checkout
-      - install_awscli
+      - install-awscli
       - run:
           name: Ensure back-end infrastructure exists
           command: |
@@ -188,12 +181,12 @@ jobs:
               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
 
       - run:
-          name: Ensure front-end infrastructure exist
+          name: Ensure front-end infrastructure exists
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/frontend.yml \
               --tags project=udapeople \
-              --stack-name "udapepole-Frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
 
       - run:
@@ -218,8 +211,7 @@ jobs:
       - image: cimg/base:stable
     steps:
       - checkout
-      - install_awscli
-      - install_ansible
+      - install-ansible
       - add_ssh_keys:
           fingerprints: ["46:bc:eb:ec:20:24:73:b8:31:3e:65:94:81:af:9f:25"]
       - attach_workspace:
@@ -231,36 +223,42 @@ jobs:
             cat inventory.txt
             ansible-playbook -i inventory.txt configure-server.yml
 
+      - destroy-environment
+      # Here's where you will add some code to rollback on failure
+
   run-migrations:
     docker:
       - image: cimg/node:13.8.0
     steps:
       - checkout
-      - install_awscli
+      - install-awscli
       - run:
           name: Run migrations
           command: |
             cd backend
             npm install
             npm run migrations > migrations_dump.txt
-
       - run:
-          name: Send migration results to memstash
+          name: Send migration status to kvdb.io
           command: |
             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
-             curl https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+              curl https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
             fi
+
       - destroy-environment
       - revert-migrations
 
+      #nothing
+      # Here's where you will add some code to rollback on failure
+  #
   deploy-frontend:
     docker:
       - image: cimg/base:stable
     steps:
       - checkout
-      - install_awscli
-      - install_nodejs
+      - install-awscli
+      - install-nodejs
       - restore_cache:
           keys: [frontend-deps]
       - run:
@@ -275,6 +273,7 @@ jobs:
               --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
               --query 'Reservations[*].Instances[*].PublicIpAddress' \
               --output text)
+
             echo "API_URL=http://${BACKEND_PUBLIC_IP}:3030" >> frontend/.env
             cat frontend/.env
       - run:
@@ -283,6 +282,7 @@ jobs:
             cd frontend
             npm run build
             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+
       - destroy-environment
       - revert-migrations
 
@@ -291,9 +291,9 @@ jobs:
       - image: cimg/base:stable
     steps:
       - checkout
-      - install_awscli
-      - install_ansible
-      - install_nodejs
+      - install-awscli
+      - install-ansible
+      - install-nodejs
       - add_ssh_keys:
           fingerprints: ["46:bc:eb:ec:20:24:73:b8:31:3e:65:94:81:af:9f:25"]
       - attach_workspace:
@@ -306,19 +306,21 @@ jobs:
             cd backend
             npm install
       - run:
-          name: Deploy backend
+          name: Package Backend
           command: |
             cd backend
             npm run build
             tar -czf artifact.tar.gz dist/* package*
+
             cd ..
             cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
       - run:
           name: Deploy backend
           command: |
             export TYPEORM_MIGRATIONS_DIR=./migrations
-            export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
-            export TYPEORM_MIGRATIONS=./migrations/*.ts
+            export TYPEORM_ENTITIES=./modules/domain/*/.entity.js
+            export TYPEORM_MIGRATIONS=./migrations/*.js
+
             cd .circleci/ansible
             cat inventory.txt
             ansible-playbook -i inventory.txt deploy-backend.yml
@@ -331,83 +333,71 @@ jobs:
       - image: cimg/base:stable
     steps:
       - checkout
-      - install_awscli
-      - install_nodejs
+      - install-awscli
+      - install-nodejs
       - run:
-          name: Backend smoke test
+          name: Backend smoke test.
           command: |
             BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
               --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
               --query 'Reservations[*].Instances[*].PublicIpAddress' \
               --output text)
             export API_URL=http://${BACKEND_PUBLIC_IP}:3030
-            if curl -s $API_URL/api/status | grep "ok"  
+            echo "API_URL = ${API_URL}"
+            if curl -s ${API_URL}/api/status | grep "ok"
             then
               exit 0
             else
               exit 1
             fi
+
       - run:
           name: Frontend smoke test.
           command: |
             FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
-            if curl -s $FRONTEND_WEBSITE | grep "Welcom"
-              then
-               exit 0
-            else 
-               exit 1
-            fi
-
-      - destroy-environment
-      - revert-migrations
-
-  cloudfront-update:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - run:
-          name: Save Old Workflow ID to kvdb.io
-          command: |
-            export OLD_WORKFLOW_ID=$(aws cloudformation \
-                      list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-                      --no-paginate --output text)
-            echo "Old Wokflow ID: $OLD_WORKFLOW_ID"
-            curl https://kvdb.io/${KVDB_BUCKET}/old_workflow_id -d "${OLD_WORKFLOW_ID}"
-      - run:
-          name: Update cloudfront distribution
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/cloudfront.yml \
-              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
-              --stack-name InitialStack
-      - destroy-environment
-      - revert-migrations
-
-  cleanup:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - run:
-          name: Remove old stacks and files
-          command: |
-            export STACKS=($(aws cloudformation list-stacks \
-                --query "StackSummaries[*].StackName" \
-                --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
-            echo Stack names: "${STACKS[@]}"
-            export OldWorkflowID=$(curl --insecure https://kvdb.io/${KVDB_BUCKET}/old_workflow_id)
-            echo Old Workflow ID: $OldWorkflowID 
-            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
             then
-              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
-              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+              exit 0
+            else
+              exit 1
             fi
+
+      - destroy-environment
+      - revert-migrations
+#
+#  cloudfront-update:
+#    docker:
+#      # Docker image here that supports AWS CLI
+#    steps:
+#      # Checkout code from git
+#      - run:
+#          name: Install dependencies
+#          command: |
+#            # your code here
+#      - run:
+#          name: Update cloudfront distribution
+#          command: |
+#            # your code here
+#      # Here's where you will add some code to rollback on failure
+#
+#cleanup:
+#    docker:
+#      # Docker image here
+#    steps:
+#      # Checkout code from git
+#      - run:
+#          name: Get old stack workflow id
+#          command: |
+#            # your code here
+#            export OldWorkflowID="the id here"
+#            export STACKS=[] #put the list of stacks here
+#      - run:
+#          name: Remove old stacks and files
+#          command: |
+#            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+#            then
+#              # your code here
+#            fi
 
 workflows:
   default:
@@ -422,11 +412,12 @@ workflows:
           requires: [build-backend]
       - scan-frontend:
           requires: [build-frontend]
+
       - deploy-infrastructure:
           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
           filters:
             branches:
-              only: [master]
+              only: [main]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
       - run-migrations:
@@ -437,7 +428,7 @@ workflows:
           requires: [run-migrations]
       - smoke-test:
           requires: [deploy-backend, deploy-frontend]
-      - cloudfront-update:
-          requires: [smoke-test]
-      - cleanup:
-          requires: [cloudfront-update]
+#      - cloudfront-update:
+#          requires: [smoke-test]
+#      - cleanup:
+#          requires: [cloudfront-update]
